### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by chernovroman1984** [primeroIMS/primero#75]
Unable to start docker production and development mode. It does not work as expected at all

**Comment by pnabutovsky** [comment]
Make sure you have created the file `docker/local.env`. Look at the sample files in the `docker` directory

**Comment by chernovroman1984** [comment]
Yes, I have docker/local.env with all needed modifications.

When I run ./compose.configure.sh I got this -

**Comment by chernovroman1984** [comment]
How can it work if I made step by step by this instruction and nothing works

**Comment by rbelem** [comment]
Hello @chernovroman1984 
You can try my branch https://github.com/rbelem/primero/tree/docker-for-dev

Create the env files and run
docker-compose run application primero-bootstrap
docker-compose down
docker-compose up

**Comment by rbelem** [comment]
My local.env

```
USE_LETS_ENCRYPT=false
PRIMERO_HOST=localhost
PRIMERO_SECRET_KEY_BASE=primero
POSTGRES_PASSWORD=primero
POSTGRES_DB=primero_development
DEVISE_SECRET_KEY=primero
DEVISE_JWT_SECRET_KEY=primero
PRIMERO_MESSAGE_SECRET=primero
```

If you want to specify a tag add
```
PRIMERO_TAG=v2.0.0.28
```

**Comment by chernovroman1984** [comment]
> Hello @chernovroman1984
> You can try my branch https://github.com/rbelem/primero/tree/docker-for-dev
> 
> Create the env files and run
> docker-compose run application primero-bootstrap
> docker-compose down
> docker-compose up

PLease explain - do I need to run these command above from the root of primero ?

**Comment by rbelem** [comment]
> > Hello @chernovroman1984
> > You can try my branch https://github.com/rbelem/primero/tree/docker-for-dev
> > Create the env files and run
> > docker-compose run application primero-bootstrap
> > docker-compose down
> > docker-compose up
> 
> PLease explain - do I need to run these command above from the root of primero ?

On the docker/ folder.

**Comment by chernovroman1984** [comment]
Thank you @rbelem !

**Comment by rbelem** [comment]
I will try to find what is missing then I let you know my findings.

**Comment by chernovroman1984** [comment]
> I will try to find what is missing then I let you know my findings.

Hi @rbelem !

Any update? Thank you!

**Comment by chernovroman1984** [comment]
Also I did trace debug for webpacker 9000 port process:

strace -f -e trace=network -p 17782 2>&1 
strace: Process 17782 attached with 11 threads
[pid 17782] accept4(20, NULL, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK) = 18
[pid 17782] accept4(20, NULL, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
[pid 17782] shutdown(18, SHUT_WR)       = 0

**Comment by rbelem** [comment]
> Thank you @rbelem !
> 
> I'm using suggested branch: git branch -a
> 
>     * docker-for-dev
> 
> 
> I've set local.env as yours, but when I run - docker-compose run application primero-bootstrap
> 
> Step 24/48 : RUN set -euox pipefail ; mkdir -p "$APP_ROOT/tmp/export" "$RAILS_LOG_PATH" ; mkdir -p "$APP_ROOT/tmp/exports" "$RAILS_LOG_PATH" ; rake primero:i18n_js
> ---> Running in e8fdcdf9919a
> 
>     * mkdir -p /srv/primero/application/tmp/export /srv/primero/application/log/primero
> 
>     * mkdir -p /srv/primero/application/tmp/exports /srv/primero/application/log/primero
> 
>     * rake primero:i18n_js
>       rake aborted!
>       NoMethodError: undefined method `[]' for nil:NilClass /srv/primero/application/config/initializers/locale.rb:20:in `<top (required)>'
>       /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require' /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `block in require'
>       /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:257:in `load_dependency' /usr/local/bundle/gems/activesupport-5.2.5/lib/active_support/dependencies.rb:291:in `require'
>       /srv/primero/application/lib/tasks/primero.rake:373:in `block (2 levels) in <top (required)>'
>       Tasks: TOP => primero:i18n_js
>       (See full trace by running task with --trace)
>       Rspec not installed--omitting tasks
>       ERROR: Service 'application' failed to build : The command '/bin/sh -c set -euox pipefail         ; mkdir -p "$APP_ROOT/tmp/export" "$RAILS_LOG_PATH"         ; mkdir -p "$APP_ROOT/tmp/exports" "$RAILS_LOG_PATH"         ; rake primero:i18n_js' returned a non-zero code: 1

@chernovroman1984 
It works with my branch, but when I rebase with latest development_v2 I get the same error.

**Comment by rbelem** [comment]
Working on updating the branch...

**Comment by chernovroman1984** [comment]
> Working on updating the branch...

Thank you @rbelem ! Waiting for an update from you

**Comment by rbelem** [comment]
@chernovroman1984 what browser are you using?

**Comment by chernovroman1984** [comment]
> @chernovroman1984 what browser are you using?

Chrome, Opera and Maxthon

**Comment by chernovroman1984** [comment]
Hi @rbelem ! Can I try some branch already?

**Comment by chernovroman1984** [comment]
@rbelem Please help!

**Comment by chernovroman1984** [comment]
@rbelem U tried to build your repo again:

rails aborted!
Errno::EACCES: Permission denied @ rb_sysopen - /srv/primero/application/db/schema.rb
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/railties/databases.rake:250:in `initialize'
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/railties/databases.rake:250:in `open'
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/railties/databases.rake:250:in `block (3 levels) in <top (required)>'
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/railties/databases.rake:68:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/activerecord-5.2.5/lib/active_record/railties/databases.rake:61:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/railties-5.2.5/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/local/bundle/gems/railties-5.2.5/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/local/bundle/gems/railties-5.2.5/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-5.2.5/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:schema:dump
(See full trace by running task with --trace)
ERROR: 1

**Comment by jmperalta87** [comment]
Hi All, this could be a silly question, but just finished the installation using Docker and can't login to the frontend because I don't know the user and password for it. Anyone knows? Thanks!
